### ISSUE TITLE
Error in linux 

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/simple_audio#6]
> Invalid argument(s): Failed to load dynamic library 'libsimple_audio.so': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/sani/Work/clones/flutter/simple_audio/example/build/linux/x64/debug/bundle/lib/libsimple_audio.so)

I'm on elementry os 6.1 (Ubuntu 20.04)

**Comment by erikas-taroza** [comment]
The library is compiled on Ubuntu 22.04. I think this issue is happening because the glib version is newer on 22.04.

I have updated the workflow to use 20.04. Please test by replacing `simple_audio` in your `pubspec.yaml` with:
```yaml
simple_audio:
    git:
      url: https://github.com/erikas-taroza/simple_audio.git
      ref: d0efff3
```
